### ISSUE TITLE
I made a go version

### ISSUE THREAD

**Issue by Roemerb** [mixmaxhq/cors-gate#2]
Hey guys,

Sorry to open an issue for this, but I found this package quite excellent and needed something similar myself for a web app I'm building in Go, so I made a Go version of this package. It's available at [roemerb/corsgate](https://github.com/roemerb/corsgate) if you'd ever need it.

Cheers!

**Comment by bradvogel** [comment]
Awesome! Want to add a link to the readme under a new section, perhaps "Language ports"?

**Comment by Roemerb** [comment]
Thanks! Created a PR.

**Comment by skeggse** [comment]
Thanks!
